### ISSUE TITLE
为什么我将 prefix 改成 C-k不启作用，仍然是 C-a

### ISSUE THREAD

**Issue by bao3** [wklken/k-tmux#2]
我是参照你的设定，改了以下部分，把 a 改了 k 。不过没什么用。。我退出了所有的 tmux，也执行了 tmux kill-server，也执行的 prefix - R重载配置，全都没用。求助

```
  set-option -g prefix C-k
  unbind-key C-b
  bind-key C-k send-prefix
```

**Comment by wklken** [comment]
ctrl-k已经被操作系统/其他软件占用, tmux根本接收不到
